# -*- coding: utf-8 -*-
"""NLP(Automated Email Routing).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fj4M28-TTeqr7lbqjpT5mjLGE-S952pF

pip installation
"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate scikit-learn

"""Data preparation"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile datapreparation.py
# from datasets import load_dataset
# import pandas as pd
# from sklearn.model_selection import train_test_split
# 
# def load_and_prepare_data():
#     # 1. data set load
#     ds = load_dataset("Tobi-Bueck/customer-support-tickets", split='train')
#     df = ds.to_pandas()
# 
#     # 2. 5 department filter for only english
#     target_queues = [
#         "Technical Support", "Customer Service",
#         "Billing and Payments", "Sales and Pre-Sales", "General Inquiry"
#     ]
# 
#     df = df[df['language'] == 'en']
#     df = df[df['queue'].isin(target_queues)]
# 
#     # 3. Shuffle
#     df = df.sample(frac=1, random_state=42).reset_index(drop=True)
# 
#     # 4. label mapping (BERT)
#     label2id = {label: i for i, label in enumerate(target_queues)}
#     id2label = {i: label for i, label in enumerate(target_queues)}
#     df['label'] = df['queue'].map(label2id)
# 
#     # 5. train, validation and text split (80%, 10%, 10%)
#     train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
#     val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)
# 
#     print("Label Distribution:\n", df['queue'].value_counts())
# 
#     return train_df, val_df, test_df, label2id, id2label

"""gpt 2+ prompting (frozen model)"""

import torch
from transformers import pipeline
from datapreparation import load_and_prepare_data
from tqdm import tqdm

# 1. data load
train_ds, val_ds, test_ds, label2id, id2label = load_and_prepare_data()

# 2. Frozen GPT-2 model load
pipe = pipeline("text-generation", model="distilgpt2", device=0 if torch.cuda.is_available() else -1)

# 3. function prediction (Few-Shot Prompting)
def get_gpt2_prediction_improved(subject, body):

    few_shot_examples = """
    Task: Classify emails into: Technical Support, Customer Service, Billing and Payments, Sales and Pre-Sales, General Inquiry.

    Subject: Refund request for order #123
    Body: I want a refund for my last purchase as the product is damaged.
    Department: Customer Service

    Subject: Cannot reset my password
    Body: The reset link is not working on the login page.
    Department: Technical Support

    Subject: Quote for bulk order
    Body: We are interested in buying 50 units. What is the discount?
    Department: Sales and Pre-Sales
    """

    prompt = f"""{few_shot_examples}
    Subject: {subject}
    Body: {body}
    Department:"""

    # do_sample=False and max_new_tokens reduce  3-5 so that do not come wrong result
    output = pipe(prompt, max_new_tokens=5, num_return_sequences=1, do_sample=False, pad_token_id=50256)

    response = output[0]['generated_text'].split("Department:")[-1].strip()
    return response

def evaluate_method_1():
    correct = 0
    total = len(test_ds)
    print(f"Testing Method 1 on {total} samples with Few-Shot Prompting...")

    for i in tqdm(range(total)):
        actual = test_ds.iloc[i]['queue']
        subject = test_ds.iloc[i]['subject']
        body = test_ds.iloc[i]['body']

        predicted = get_gpt2_prediction_improved(subject, body)

        # predictiction in between actual level (Case insensitive)
        if actual.lower() in predicted.lower():
            correct += 1

    accuracy = (correct / total) * 100
    return accuracy

# run and show result
method_1_acc = evaluate_method_1()
print(f"\nMethod 1 (Improved Frozen GPT-2) Final Accuracy: {method_1_acc:.2f}%")

"""Distillgpt2+ prompting"""

import torch
from transformers import pipeline
from datapreparation import load_and_prepare_data
from tqdm import tqdm

# 1. data load
train_ds, val_ds, test_ds, label2id, id2label = load_and_prepare_data()

# 2. Distillgpt2 model load (Frozen)
# 'distilgpt2' model pipeline load for text generation
pipe = pipeline("text-generation", model="distilgpt2", device=0 if torch.cuda.is_available() else -1)

def get_distillgpt2_prediction(subject, body):

    few_shot_examples = """
    Task: Classify emails into: Technical Support, Customer Service, Billing and Payments, Sales and Pre-Sales, General Inquiry.

    Subject: Refund request for order #123
    Body: I want a refund for my last purchase as the product is damaged.
    Department: Customer Service

    Subject: Cannot reset my password
    Body: The reset link is not working on the login page.
    Department: Technical Support

    Subject: Quote for bulk order
    Body: We are interested in buying 50 units. What is the discount?
    Department: Sales and Pre-Sales
    """

    prompt = f"""{few_shot_examples}
    Subject: {subject}
    Body: {body}
    Department:"""

    output = pipe(prompt, max_new_tokens=5, num_return_sequences=1, do_sample=False, pad_token_id=50256)

    response = output[0]['generated_text'].split("Department:")[-1].strip()
    return response

def evaluate_distillgpt2():
    correct = 0
    total = len(test_ds)
    print(f"Testing Distillgpt2 Prompting on {total} samples...")

    for i in tqdm(range(total)):
        actual = test_ds.iloc[i]['queue']
        subject = test_ds.iloc[i]['subject']
        body = test_ds.iloc[i]['body']

        predicted = get_distillgpt2_prediction(subject, body)

        # predictiction in between actual level (Case Insensitive)
        if actual.lower() in predicted.lower():
            correct += 1

    accuracy = (correct / total) * 100
    return accuracy

distillgpt2_prompt_acc = evaluate_distillgpt2()
print(f"\nMethod 1 (Distillgpt2+ prompting) Final Accuracy: {distillgpt2_prompt_acc:.2f}%")

"""gpt2+ fine tuning (LORA)"""

# Library and Data Load
import torch
from peft import LoraConfig, get_peft_model, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import Dataset
from datapreparation import load_and_prepare_data

# 1. Data load
train_ds, val_ds, test_ds, label2id, id2label = load_and_prepare_data()

# 2. GPT2 Model and Tokenizer setup
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

# Data Preprocessing
def tokenize_function(examples):

    texts = [f"Subject: {s}\nBody: {b}\nDepartment: {q}"
             for s, b, q in zip(examples['subject'], examples['body'], examples['queue'])]
    return tokenizer(texts, truncation=True, padding="max_length", max_length=128)

train_dataset = Dataset.from_pandas(train_ds).map(tokenize_function, batched=True)
val_dataset = Dataset.from_pandas(val_ds).map(tokenize_function, batched=True)

# LoRA configuration
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["c_attn"],
    lora_dropout=0.05,
    task_type=TaskType.CAUSAL_LM
)


base_model = AutoModelForCausalLM.from_pretrained(model_name)
lora_model = get_peft_model(base_model, lora_config)

# model train
training_args = TrainingArguments(
    output_dir="./gpt2-full-lora-router",
    per_device_train_batch_size=4,
    eval_strategy="epoch",
    learning_rate=2e-4,
    num_train_epochs=1,
    save_strategy="epoch",
    logging_steps=10,
    fp16=True if torch.cuda.is_available() else False,
    report_to="none"
)

trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
)

print("\n--- GPT-2 Full Fine-tuning is starting... ---")
trainer.train()

"""Accuracy test"""

def get_gpt2_lora_prediction(subject, body):
    prompt = f"Subject: {subject}\nBody: {body}\nDepartment:"
    inputs = tokenizer(prompt, return_tensors="pt").to(lora_model.device)

    with torch.no_grad():
        output_tokens = lora_model.generate(**inputs, max_new_tokens=5, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.decode(output_tokens[0], skip_special_tokens=True)
    return response.split("Department:")[-1].strip()


correct = 0
total = len(test_ds)
print(f"Testing on {total} samples...")

for i in range(total):
    actual = test_ds.iloc[i]['queue']
    pred = get_gpt2_lora_prediction(test_ds.iloc[i]['subject'], test_ds.iloc[i]['body'])
    if actual.lower() in pred.lower():
        correct += 1

final_acc = (correct / total) * 100
print(f"\nMethod 2 (Full GPT-2 LoRA) Accuracy: {final_acc:.2f}%")

"""DistilGpt2+ fine tuning"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate scikit-learn

# Commented out IPython magic to ensure Python compatibility.
# # data preparation
# %%writefile datapreparation.py
# from datasets import load_dataset
# import pandas as pd
# from sklearn.model_selection import train_test_split
# 
# def load_and_prepare_data():
#     # 1. data set load
#     ds = load_dataset("Tobi-Bueck/customer-support-tickets", split='train')
#     df = ds.to_pandas()
# 
#     # 2. 5 department filter for only english
#     target_queues = [
#         "Technical Support", "Customer Service",
#         "Billing and Payments", "Sales and Pre-Sales", "General Inquiry"
#     ]
# 
#     df = df[df['language'] == 'en']
#     df = df[df['queue'].isin(target_queues)]
# 
#     # 3. Shuffle
#     df = df.sample(frac=1, random_state=42).reset_index(drop=True)
# 
#     # 4. label mapping (BERT)
#     label2id = {label: i for i, label in enumerate(target_queues)}
#     id2label = {i: label for i, label in enumerate(target_queues)}
#     df['label'] = df['queue'].map(label2id)
# 
#     # 5. train, validation and text split (80%, 10%, 10%)
#     train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
#     val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)
# 
#     print("Label Distribution:\n", df['queue'].value_counts())
# 
#     return train_df, val_df, test_df, label2id, id2label

# data load
!pip install -q transformers datasets peft accelerate evaluate

import torch
from peft import LoraConfig, get_peft_model, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import Dataset
from datapreparation import load_and_prepare_data
import os

train_ds, val_ds, test_ds, label2id, id2label = load_and_prepare_data()

model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

# data processing
def tokenize_function(examples):

    texts = [f"Subject: {s}\nBody: {b}\nDepartment: {q}"
             for s, b, q in zip(examples['subject'], examples['body'], examples['queue'])]
    return tokenizer(texts, truncation=True, padding="max_length", max_length=128)

train_dataset = Dataset.from_pandas(train_ds).map(tokenize_function, batched=True)
val_dataset = Dataset.from_pandas(val_ds).map(tokenize_function, batched=True)

# LoRA config

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["c_attn"],
    lora_dropout=0.05,
    task_type=TaskType.CAUSAL_LM
)

base_model = AutoModelForCausalLM.from_pretrained(model_name)
lora_model = get_peft_model(base_model, lora_config)

lora_model.print_trainable_parameters()

# model train
training_args = TrainingArguments(
    output_dir="./distilgpt2-plus-fast",
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    eval_strategy="no",
    learning_rate=3e-4,
    num_train_epochs=1,
    save_strategy="no",
    logging_steps=50,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none"
)

trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
)

print("\n--- Starting Fast DistilGpt2+ Fine-tuning ---")
trainer.train()

# accuracy test
import torch
from tqdm import tqdm

def get_distilgpt2_plus_prediction(subject, body):

    prompt = f"Subject: {subject}\nBody: {body}\nDepartment:"

    inputs = tokenizer(prompt, return_tensors="pt").to(lora_model.device)

    with torch.no_grad():
        output_tokens = lora_model.generate(
            **inputs,
            max_new_tokens=5,
            pad_token_id=tokenizer.eos_token_id,
            do_sample=False
        )

    full_response = tokenizer.decode(output_tokens[0], skip_special_tokens=True)
    prediction = full_response.split("Department:")[-1].strip()
    return prediction

correct = 0
total = len(test_ds)
print(f"Evaluating DistilGpt2+ on {total} samples...")

for i in tqdm(range(total)):
    actual_label = test_ds.iloc[i]['queue']
    subject = test_ds.iloc[i]['subject']
    body = test_ds.iloc[i]['body']

    predicted_label = get_distilgpt2_plus_prediction(subject, body)

    if actual_label.lower() in predicted_label.lower():
        correct += 1

final_accuracy = (correct / total) * 100
print(f"\n--- Evaluation Results ---")
print(f"Total Test Samples: {total}")
print(f"Correct Predictions: {correct}")
print(f"DistilGpt2+ Final Accuracy: {final_accuracy:.2f}%")

"""DistilBERT+ classifier"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate scikit-learn

# Commented out IPython magic to ensure Python compatibility.
# # data preparation
# %%writefile datapreparation.py
# from datasets import load_dataset
# import pandas as pd
# from sklearn.model_selection import train_test_split
# 
# def load_and_prepare_data():
#     # 1. data set load
#     ds = load_dataset("Tobi-Bueck/customer-support-tickets", split='train')
#     df = ds.to_pandas()
# 
#     # 2. 5 department filter for only english
#     target_queues = [
#         "Technical Support", "Customer Service",
#         "Billing and Payments", "Sales and Pre-Sales", "General Inquiry"
#     ]
# 
#     df = df[df['language'] == 'en']
#     df = df[df['queue'].isin(target_queues)]
# 
#     # 3. Shuffle
#     df = df.sample(frac=1, random_state=42).reset_index(drop=True)
# 
#     # 4. label mapping (BERT)
#     label2id = {label: i for i, label in enumerate(target_queues)}
#     id2label = {i: label for i, label in enumerate(target_queues)}
#     df['label'] = df['queue'].map(label2id)
# 
#     # 5. train, validation and text split (80%, 10%, 10%)
#     train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
#     val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)
# 
#     print("Label Distribution:\n", df['queue'].value_counts())
# 
#     return train_df, val_df, test_df, label2id, id2label

# data load
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
from datapreparation import load_and_prepare_data
import numpy as np
import evaluate

train_ds, val_ds, test_ds, label2id, id2label = load_and_prepare_data()

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# data processing
def preprocess_function(examples):
    inputs = [f"{s} [SEP] {b}" for s, b in zip(examples['subject'], examples['body'])]
    tokenized = tokenizer(inputs, truncation=True, padding="max_length", max_length=128)
    tokenized["labels"] = [label2id[label] for label in examples["queue"]]
    return tokenized

train_dataset = Dataset.from_pandas(train_ds).map(preprocess_function, batched=True)
val_dataset = Dataset.from_pandas(val_ds).map(preprocess_function, batched=True)

# model and accuracy metric setup
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=len(label2id), id2label=id2label, label2id=label2id
)

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# model train
training_args = TrainingArguments(
    output_dir="./distilbert-plus-80-accuracy",
    learning_rate=3e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True if torch.cuda.is_available() else False,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

print("\n--- Training DistilBERT+ Classifier for 80% Accuracy ---")
trainer.train()

# accuracy test
test_dataset = Dataset.from_pandas(test_ds).map(preprocess_function, batched=True)
results = trainer.evaluate(test_dataset)

print(f"\nDistilBERT+ Classifier Final Accuracy: {results['eval_accuracy']*100:.2f}%")

"""Comparison Table and chart"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Method Name': [
        'Method 1: Frozen GPT-2 (Prompting)',
        'Method 1b: Distillgpt2 (Prompting)',
        'Method 2: GPT-2 LoRA (Fine-tuned)',
        'Method 3: DistilGpt2+ (Fine-tuned)',
        'Method 4: DistilBERT+ Classifier'
    ],
    'Accuracy (%)': [22.63, 22.63, 63.07, 52.32, 76.58],
    'Training Time': ['N/A (Inference Only)', 'N/A (Inference Only)', '3.3 Hours', '3.1 Hours', '6.9 Hours'],
    'Complexity': ['Low', 'Low', 'High', 'Medium', 'Medium']
}

df = pd.DataFrame(data)


print("--- Final Model Comparison Table ---")
print(df.to_string(index=False))

# chart
plt.figure(figsize=(12, 6))
sns.set_style("whitegrid")
bars = sns.barplot(x='Accuracy (%)', y='Method Name', data=df, palette='magma')

for i in bars.containers:
    bars.bar_label(i, fmt='%.2f%%', padding=5)

plt.title('Comparison of LLM Agents for Email Routing (Final Results)', fontsize=15)
plt.xlabel('Test Accuracy (%)', fontsize=12)
plt.ylabel('Method Name', fontsize=12)
plt.xlim(0, 100)
plt.tight_layout()
plt.show()